name: Call a reusable workflow

on:
  push:
    branches:
      - main

jobs:
  call-workflow-dev:
    uses: ./.github/workflows/reusable_terraform_plan.yml
    with:
      environment: 'dev'
      working_directory: './terraform'
      aws_region: 'eu-west-2'
      terraform_version: '1.0.0'
      backend_config_key: 'state/dev/terraform.tfstate'
      workspace: 'dev'
      var_file: 'environments/dev.tfvars'
    secrets: inherit

  call-workflow-staging:
    needs: call-workflow-dev
    uses: ./.github/workflows/reusable_terraform_plan.yml
    with:
      environment: 'staging'
      working_directory: './terraform'
      aws_region: 'eu-west-2'
      terraform_version: '1.0.0'
      backend_config_key: 'state/staging/terraform.tfstate'
      workspace: 'staging'
      var_file: 'environments/staging.tfvars'
    secrets: inherit

  call-workflow-prod:
    needs: call-workflow-staging
    uses: ./.github/workflows/reusable_terraform_plan.yml
    with:
      environment: 'prod'
      working_directory: './terraform'
      aws_region: 'eu-west-2'
      terraform_version: '1.0.0'
      backend_config_key: 'state/prod/terraform.tfstate'
      workspace: 'prod'
      var_file: 'environments/prod.tfvars'
    secrets: inherit