name: Trigger Terraform Plan Apply on Push

on:
      push:
        branches:
          - main

      workflow_dispatch:
   
jobs:
  trigger_terraform_pipeline:
    name: Trigger Terraform Pipeline
    runs-on: ubuntu-latest
    
    steps:
      - name: Trigger Terraform Plan Apply
        uses: peter-evans/repository-dispatch@v1
        with:
          token: ${{ secrets.PAT_TOKEN }}
          repository: km-practice/reusable-terraform-plan-apply
          event-type: terraform-plan-apply
          client-payload: '{"ref": "main"}'